/**
 * THE WORDS MEIKYUU SAYS, in English and Japanese: what a screen reader hears of a drawing, what the
 * buttons and the lines under a playable board say, and the names of the shapes and the ways to play.
 * Plain data, so a page can read them, replace a few, or add a language of its own beside these two.
 *
 * `{name}` in a line is a value filled in; a line `foo` that has a `fooOne` beside it is said as
 * `fooOne` when its `{n}` is 1.
 */
export type MeikyuuLanguage = "en" | "ja";

export const MEIKYUU_STRINGS: Record<MeikyuuLanguage, Record<string, string>> = {
  en: {
    mazeLabel: "{shape} maze of {n} cells. {play}",
    arrowsLabel: "Arrow puzzle of {n} arrows on a {shape} board.",
    shape_square: "Square",
    shape_hex: "Hexagons",
    shape_triangle: "Triangles",
    shape_circle: "Circle",
    shape_heart: "Heart",
    shape_leaf: "Leaf",
    shape_star: "Star",
    shape_ring: "Ring",
    shape_diamond: "Diamond",
    shape_cross: "Cross",
    shape_moon: "Moon",
    shape_hexagon: "Hexagon",
    shape_pyramid: "Pyramid",
    mode_enter_leave: "Enter and leave",
    mode_to_goal: "Find the goal",
    mode_centre_out: "Out from the centre",
    mode_keys: "Collect the keys",
    play_enter_leave: "Draw a line from the way in to the way out.",
    play_to_goal: "Draw a line from the green start to the gold goal.",
    play_centre_out: "Draw a line from the middle out through the door in the outer wall.",
    play_keys: "Pick up every key, then draw out through the door in the outer wall.",
    kind_maze: "Mazes",
    kind_arrows: "Arrows",
    kind_mixed: "Mixed",
    undo: "Undo",
    restart: "Restart",
    hint: "Hint",
    fit: "Fit",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    zoomLabel: "Zoom the board",
    pan: "Move",
    panLabel: "Drag the board to move it, instead of drawing",
    turn: "Turn",
    turnLabel: "Turn the board a quarter",
    tabArrows: "Arrows",
    tabMaze: "Labyrinth",
    tabsLabel: "Which board to look at",
    hintStart: "Press the green start and draw.",
    hintAhead: "Follow the glow.",
    hintBack: "Draw back {n} cells, then follow the glow.",
    hintBackOne: "Draw back 1 cell, then follow the glow.",
    drawn: "{n} cells drawn.",
    drawnOne: "{n} cell drawn.",
    notStarted: "Press the start and draw.",
    keysOf: "Keys {k} of {total}.",
    solved: "Solved in {n} strokes.",
    solvedOne: "Solved in 1 stroke.",
    needKeys: "The goal is reached, but {n} keys are still to find.",
    needKeysOne: "The goal is reached, but 1 key is still to find.",
    arrowsLeft: "{n} arrows left.",
    arrowsLeftOne: "1 arrow left.",
    hearts: "Hearts: {n} of {total}.",
    arrowsHint: "Tap an arrow to send it off the board the way it points.",
    arrowsFlew: "Away it goes.",
    arrowsBlocked: "Blocked: another arrow is in the way, and a heart is lost.",
    arrowsLocked: "Locked. Find the unlock button in the labyrinth.",
    arrowsWaiting: "A locked arrow is holding this one up. Find the unlock button in the labyrinth.",
    arrowsUnlocked: "Unlocked! The locked arrows are free to go.",
    arrowsCleared: "Cleared! Every arrow is off the board.",
    arrowsLost: "Out of hearts. Restart to try again.",
    arrowsLostAway: "The arrows are out of hearts. Go back to them and press Restart.",
    lockedCount: "{n} locked.",
    button: "Unlock button",
    mazeForButton: "Draw a line from the green start to the unlock button.",
    heart: "heart",
    stone: "Stone",
    stoneLabel: "Stone mode: tap a cell beside your line to lay a stone there, or a stone to take it up",
    stoneHow: "Stone mode. Tap a cell beside your line, up to {n} cells away along the passages, to lay a stone the line cannot enter. Tap a stone to take it up.",
    stonesLeft: "Stones left: {n}.",
    stonesLeftOne: "Stones left: 1.",
    stonesFree: "Stones laid: {n}.",
    stonesFreeOne: "Stones laid: 1.",
    stoneLaid: "Stone laid. The line cannot go in there. Tap it to take it up.",
    stoneTaken: "Stone taken up.",
    stoneFar: "Too far from your line. A stone goes on a passage up to {n} cells along from it.",
    stoneOnLine: "That cell is on your line.",
    stoneEnd: "A stone cannot go on the start or the goal.",
    stoneLimit: "No stones left. Tap a stone to take it up and lay it again.",
    stoneNoLine: "Draw a line first. A stone goes beside it.",
    stoneSolved: "The maze is solved.",
    stoneDrawing: "Lift your finger first.",
    solidLabel: "{shape} maze of {n} cells. {play}",
    solid_cube: "Cube",
    solid_sphere: "Sphere",
    solid_tetrahedron: "Tetrahedron",
    solid_octahedron: "Octahedron",
    solid_icosahedron: "Icosahedron",
    play_solid: "Draw a line from the green start to the gold goal over the surface. Turn the solid to follow your line round it.",
    solidHow: "Draw from the green start. Drag away from your line, or use the arrows, to turn the solid. It also turns by itself when your line nears the edge of the side you can see.",
    solidHidden: "The end of your line is out of sight. Turn the solid, or press Face me.",
    turnLeft: "Turn left",
    turnRight: "Turn right",
    turnUp: "Turn up",
    turnDown: "Turn down",
    turnPadLabel: "Turn the solid",
    faceMe: "Face me",
    faceMeLabel: "Turn the solid so that the end of your line faces you",
    solidTurnMode: "Turn only",
    solidTurnModeLabel: "Drag anywhere to turn the solid, instead of drawing",
  },
  ja: {
    mazeLabel: "{shape}の迷宮（{n}マス）。{play}",
    arrowsLabel: "{shape}の盤に{n}本の矢が並ぶ矢印パズル。",
    shape_square: "四角",
    shape_hex: "六角",
    shape_triangle: "三角",
    shape_circle: "円",
    shape_heart: "ハート",
    shape_leaf: "葉",
    shape_star: "星",
    shape_ring: "輪",
    shape_diamond: "ひし形",
    shape_cross: "十字",
    shape_moon: "月",
    shape_hexagon: "大六角形",
    shape_pyramid: "ピラミッド",
    mode_enter_leave: "入口から出口へ",
    mode_to_goal: "ゴールを探す",
    mode_centre_out: "中心から外へ",
    mode_keys: "鍵を集めて出る",
    play_enter_leave: "入口から出口まで、線を引きます。",
    play_to_goal: "緑のスタートから金色のゴールまで、線を引きます。",
    play_centre_out: "中心から、外壁の出口まで、線を引きます。",
    play_keys: "鍵をすべて拾ってから、外壁の出口まで線を引きます。",
    kind_maze: "迷路",
    kind_arrows: "矢印",
    kind_mixed: "ミックス",
    undo: "もどす",
    restart: "やり直す",
    hint: "ヒント",
    fit: "全体",
    zoomIn: "拡大",
    zoomOut: "縮小",
    zoomLabel: "盤を拡大・縮小",
    pan: "移動",
    panLabel: "線を引かずに、盤をドラッグして動かす",
    turn: "回す",
    turnLabel: "盤を4分の1回す",
    tabArrows: "矢印",
    tabMaze: "迷宮",
    tabsLabel: "見る盤を選ぶ",
    hintStart: "緑のスタートを押して、線を引きます。",
    hintAhead: "光っているところをたどります。",
    hintBack: "{n}マスもどってから、光っているところをたどります。",
    hintBackOne: "1マスもどってから、光っているところをたどります。",
    drawn: "{n}マス描きました。",
    drawnOne: "{n}マス描きました。",
    notStarted: "スタートを押して、線を引きます。",
    keysOf: "鍵 {k}／{total}。",
    solved: "{n}回の線で解けました。",
    solvedOne: "1回の線で解けました。",
    needKeys: "ゴールに着きましたが、鍵があと{n}個残っています。",
    needKeysOne: "ゴールに着きましたが、鍵があと1個残っています。",
    arrowsLeft: "矢はあと{n}本。",
    arrowsLeftOne: "矢はあと1本。",
    hearts: "ハート：{n}／{total}。",
    arrowsHint: "矢をタップすると、向いている方向へ盤の外に飛んでいきます。",
    arrowsFlew: "飛んでいきました。",
    arrowsBlocked: "ほかの矢が邪魔をしています。ハートが1つ減りました。",
    arrowsLocked: "鍵がかかっています。迷宮の解除ボタンを探しましょう。",
    arrowsWaiting: "鍵のかかった矢のせいで動かせません。迷宮の解除ボタンを探しましょう。",
    arrowsUnlocked: "解除しました。鍵のかかった矢が動かせます。",
    arrowsCleared: "クリア。すべての矢が盤から出ました。",
    arrowsLost: "ハートがなくなりました。やり直してください。",
    arrowsLostAway: "矢のハートがなくなりました。矢に戻って、やり直してください。",
    lockedCount: "鍵つきの矢が{n}本あります。",
    button: "解除ボタン",
    mazeForButton: "緑のスタートから解除ボタンまで、線を引きます。",
    heart: "ハート",
    stone: "石",
    stoneLabel: "石のモード：線のとなりのマスをタップすると石を置き、石をタップすると取り除く",
    stoneHow: "石のモードです。線のとなりのマス（通路づたいに{n}マスまで）をタップすると、線が入れない石を置けます。石をタップすると取り除きます。",
    stonesLeft: "石はあと{n}個。",
    stonesLeftOne: "石はあと1個。",
    stonesFree: "石を{n}個置きました。",
    stonesFreeOne: "石を1個置きました。",
    stoneLaid: "石を置きました。線はそこに入れません。タップで取り除けます。",
    stoneTaken: "石を取り除きました。",
    stoneFar: "線から遠すぎます。石は線から通路づたいに{n}マスまでに置けます。",
    stoneOnLine: "そのマスは線の上です。",
    stoneEnd: "スタートとゴールには石を置けません。",
    stoneLimit: "石がもうありません。石をタップして取り除くと、また置けます。",
    stoneNoLine: "先に線を引いてください。石は線のとなりに置きます。",
    stoneSolved: "迷宮は解けています。",
    stoneDrawing: "いったん指を離してください。",
    solidLabel: "{shape}の迷宮（{n}マス）。{play}",
    solid_cube: "立方体",
    solid_sphere: "球",
    solid_tetrahedron: "正四面体",
    solid_octahedron: "正八面体",
    solid_icosahedron: "正二十面体",
    play_solid: "緑のスタートから金色のゴールまで、表面をたどって線を引きます。線を追って立体を回します。",
    solidHow: "緑のスタートから線を引きます。線から離れたところをドラッグするか、矢印を使うと立体が回ります。線が見えている面の端に近づくと、立体はひとりでに回ります。",
    solidHidden: "線の先が見えない面にあります。立体を回すか「こちらへ」を押してください。",
    turnLeft: "左へ回す",
    turnRight: "右へ回す",
    turnUp: "上へ回す",
    turnDown: "下へ回す",
    turnPadLabel: "立体を回す",
    faceMe: "こちらへ",
    faceMeLabel: "線の先がこちらを向くように立体を回す",
    solidTurnMode: "回すだけ",
    solidTurnModeLabel: "線を引かずに、どこをドラッグしても立体を回す",
  },
};

/** The language a `lang` attribute asks for: Japanese for any `ja`, English for everything else. */
export function meikyuuLanguageOf(tag: string | null | undefined): MeikyuuLanguage {
  return String(tag ?? "").toLowerCase().startsWith("ja") ? "ja" : "en";
}

/** A line in a language, with its `{name}` values filled in, and its `One` form when `n` is 1. */
export function meikyuuSay(language: MeikyuuLanguage, key: string, values: Record<string, string | number> = {}): string {
  const table = MEIKYUU_STRINGS[language];
  const one = values["n"] === 1 && `${key}One` in table ? `${key}One` : key;
  const line = table[one] ?? MEIKYUU_STRINGS.en[one] ?? table[key] ?? MEIKYUU_STRINGS.en[key] ?? key;
  return line.replace(/\{(\w+)\}/g, (whole, name: string) => (name in values ? String(values[name]) : whole));
}
